<?php
$products=isset($data['products'])&&is_array($data['products'])?$data['products']:[
 ['slug'=>'royal-plum-theme','name'=>'Royal Plum Theme','description'=>'A permanent fixed premium purple visual theme.','price_cents'=>399,'icon'=>'✦','owned'=>false],
 ['slug'=>'royal-onion-profile','name'=>'Royal Onion Profile Frame','description'=>'A permanent fixed royal frame for your profile.','price_cents'=>299,'icon'=>'♛','owned'=>false],
 ['slug'=>'cozy-fireplace-theme','name'=>'Cozy Fireplace Theme','description'=>'A permanent fixed visual theme for your lounge.','price_cents'=>399,'icon'=>'♨','owned'=>false],
 ['slug'=>'animated-crown','name'=>'Animated Crown Decoration','description'=>'A subtle, reduced-motion-aware crown profile decoration.','price_cents'=>249,'icon'=>'♕','owned'=>false],
 ['slug'=>'ad-free-lifetime','name'=>'Lifetime Ad-Free Upgrade','description'=>'Remove display advertisements from this account permanently.','price_cents'=>1999,'icon'=>'◌','owned'=>false],
 ['slug'=>'founder-badge','name'=>'Founder Supporter Badge','description'=>'A fixed supporter badge for your profile. No gameplay benefit.','price_cents'=>199,'icon'=>'◆','owned'=>false],
];
?>
<header class="page-hero"><div class="shell page-hero-inner"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="<?= $url('home', [], '/') ?>">Parlor</a><span aria-hidden="true">/</span><span>Cosmetic shop</span></nav><p class="eyebrow">Fixed items, clearly described</p><h1>The Parlor shop</h1><p class="lede">Original themes, frames, and other nonconsumable entertainment extras. No paid Coins, spins, bets, random rewards, loot boxes, or odds boosts.</p></div></header>
<section class="section shell"><div class="section-heading"><div><h2>Cosmetic collection</h2><p>Every purchase shows its fixed contents and refund policy before checkout.</p></div><a class="button button-ghost" href="<?= $url('billing.history', [], '/billing/history') ?>">Purchase history</a></div><div class="shop-grid"><?php foreach($products as $product): ?><article class="product-card card"><div class="product-preview" aria-hidden="true"><?= $esc($product['icon']) ?></div><div class="product-body"><span class="tag"><?= !empty($product['owned'])?'Owned':'Fixed contents' ?></span><h3><?= $esc($product['name']) ?></h3><p class="muted"><?= $esc($product['description']) ?></p><div class="split"><strong class="product-price">$<?= $esc(number_format(((int)$product['price_cents'])/100,2)) ?></strong><?php if(!empty($product['owned'])): ?><a class="button button-small button-ghost" href="<?= $url('settings.index', [], '/settings') ?>">Use item</a><?php else: ?><a class="button button-small button-gold" href="<?= $url('billing.checkout', ['product'=>$product['slug']], '/billing/checkout?product='.rawurlencode($product['slug'])) ?>">View details</a><?php endif; ?></div></div></article><?php endforeach; ?></div></section>
<section class="section-tight shell"><div class="callout"><strong>Commercial licensing is handled separately.</strong> Custom games and software licenses require an inquiry, Adult Owner review, and a separate written agreement—not an automatic consumer shop payment. <a href="<?= $url('licensing.index', [], '/licensing') ?>">Start a licensing inquiry</a>.</div></section>
