<?php
/** @var array<int,array<string,mixed>> $games */
return [
    ['slug'=>'plinko','name'=>'Plinko','category'=>'Arcade','description'=>'Guide a falling chip through a field of pegs toward a fictional prize bin.'],
    ['slug'=>'classic-slots','name'=>'Parlor Reels','category'=>'Slots','description'=>'Three cozy reels with original Royal Onion symbols and a clear paytable.'],
    ['slug'=>'video-slots','name'=>'Velvet Five','category'=>'Slots','description'=>'Five reels, original lounge symbols, and skip-friendly animations.'],
    ['slug'=>'blackjack','name'=>'Parlor Twenty-One','category'=>'Table','description'=>'Classic blackjack rules with clear hand totals and an optional strategy guide.'],
    ['slug'=>'european-roulette','name'=>'European Roulette','category'=>'Wheel','description'=>'Single-zero roulette with complete inside and outside bet disclosures.'],
    ['slug'=>'american-roulette','name'=>'American Roulette','category'=>'Wheel','description'=>'Double-zero roulette with clearly different probabilities and house edge.'],
    ['slug'=>'baccarat','name'=>'Baccarat','category'=>'Table','description'=>'Player, banker, and tie practice using standard third-card drawing rules.'],
    ['slug'=>'craps','name'=>'Parlor Dice Table','category'=>'Dice','description'=>'A guided craps table with pass, come, place, and odds explanations.'],
    ['slug'=>'video-poker','name'=>'Velvet Video Poker','category'=>'Cards','description'=>'Jacks or Better, Deuces Wild, and Bonus Poker with visible paytables.'],
    ['slug'=>'texas-holdem','name'=>'Hold’em Practice Room','category'=>'Poker','description'=>'Play Texas Hold’em against clearly labeled computer opponents.'],
    ['slug'=>'three-card-poker','name'=>'Three Card Poker','category'=>'Poker','description'=>'Ante-play and pair-plus practice with compact three-card hands.'],
    ['slug'=>'caribbean-stud','name'=>'Island Five Stud','category'=>'Poker','description'=>'Five-card stud-inspired table play against the house dealer.'],
    ['slug'=>'casino-war','name'=>'High Card Duel','category'=>'Cards','description'=>'A quick high-card comparison with the tie choice explained before play.'],
    ['slug'=>'red-dog','name'=>'Red Dog Practice','category'=>'Cards','description'=>'Predict whether a third card will fall between two ranks.'],
    ['slug'=>'let-it-ride','name'=>'Let It Rest','category'=>'Poker','description'=>'A relaxed five-card poker variant with two optional fictional wagers.'],
    ['slug'=>'pai-gow-poker','name'=>'Pai Gow Poker','category'=>'Poker','description'=>'Arrange seven cards into valid high and low poker hands.'],
    ['slug'=>'hi-lo','name'=>'Hi-Lo','category'=>'Cards','description'=>'Choose whether the next card will be higher or lower, with ties disclosed.'],
    ['slug'=>'five-card-draw','name'=>'Five Card Draw','category'=>'Poker','description'=>'Classic draw poker against transparent computer difficulty levels.'],
    ['slug'=>'teen-patti','name'=>'Three-Card Practice','category'=>'Cards','description'=>'A clearly explained Teen Patti-style practice game using fictional coins.'],
    ['slug'=>'blackjack-switch','name'=>'Twin Hand Switch','category'=>'Table','description'=>'An original two-hand twenty-one practice variant with card switching.'],
    ['slug'=>'sic-bo','name'=>'Sic Bo','category'=>'Dice','description'=>'Three-dice outcomes with small, big, total, triple, and combination bets.'],
    ['slug'=>'keno','name'=>'Keno','category'=>'Numbers','description'=>'Pick numbers and compare them with a server-generated fictional draw.'],
    ['slug'=>'bingo','name'=>'Parlor Bingo','category'=>'Numbers','description'=>'A calm, accessible bingo card with announced and visual number calls.'],
    ['slug'=>'mines','name'=>'Moonlit Mines','category'=>'Arcade','description'=>'Reveal safe tiles or collect a fictional score before finding a mine.'],
    ['slug'=>'over-under-dice','name'=>'Over / Under Dice','category'=>'Dice','description'=>'Select a threshold and see the exact chance before rolling.'],
    ['slug'=>'coin-flip','name'=>'Royal Coin Flip','category'=>'Arcade','description'=>'A simple fifty-fifty fictional coin toss with no paid play.'],
    ['slug'=>'prize-wheel','name'=>'Parlor Prize Wheel','category'=>'Wheel','description'=>'Spin a clearly segmented wheel for free fictional rewards.'],
    ['slug'=>'number-draw','name'=>'Number Draw','category'=>'Numbers','description'=>'Choose a number range and compare with a server-authoritative draw.'],
    ['slug'=>'pachinko','name'=>'Pocket Pachinko','category'=>'Arcade','description'=>'Drop a ball through a compact peg board toward scoring pockets.'],
    ['slug'=>'horse-racing','name'=>'Velvet Derby','category'=>'Simulation','description'=>'A fictional race simulation with transparent odds and no real betting.'],
    ['slug'=>'scratch-cards','name'=>'Free Scratch Cards','category'=>'Casual','description'=>'Free daily scratch-style cards with fixed disclosed fictional rewards.'],
    ['slug'=>'memory-match','name'=>'Memory Match','category'=>'Casual','description'=>'Match original Parlor symbols in a no-wager memory challenge.'],
    ['slug'=>'klondike-solitaire','name'=>'Klondike Solitaire','category'=>'Solitaire','description'=>'Classic Klondike with undo, keyboard movement, and no fictional wager.'],
    ['slug'=>'pyramid-solitaire','name'=>'Pyramid Solitaire','category'=>'Solitaire','description'=>'Clear card pairs totaling thirteen in a cozy lounge layout.'],
    ['slug'=>'tripeaks-solitaire','name'=>'TriPeaks Solitaire','category'=>'Solitaire','description'=>'Clear three peaks by selecting cards one rank above or below.'],
    ['slug'=>'freecell','name'=>'FreeCell','category'=>'Solitaire','description'=>'Open-information solitaire with keyboard controls and unlimited undo.'],
    ['slug'=>'higher-lower','name'=>'Higher-or-Lower Streak','category'=>'Casual','description'=>'Build a fictional streak by reading visible card probabilities.'],
    ['slug'=>'gem-drop','name'=>'Gem Drop','category'=>'Casual','description'=>'Arrange original jewel shapes in a relaxed score-chasing puzzle.'],
    ['slug'=>'lucky-cups','name'=>'Lucky Cups','category'=>'Casual','description'=>'Follow the hidden onion token through a fair server-chosen shuffle.'],
    ['slug'=>'treasure-tiles','name'=>'Treasure Tiles','category'=>'Casual','description'=>'Reveal a small board of original lounge treasures for fictional points.'],
];
