<?php
return [
 'title'=>'Privacy Policy','version'=>'draft-1','effective_date'=>'{{EFFECTIVE_DATE}}','summary'=>'How {{SITE_NAME}} collects, uses, protects, and gives you choices about personal information.','important_notice'=>'{{SITE_NAME}} does not use precise location, fingerprint visitors, store raw IP addresses indefinitely, or send user data and game activity to an AI service.',
 'sections'=>[
  ['heading'=>'1. Who this policy covers','paragraphs'=>['This policy applies to visitors, guests, registered members, and people who contact {{SITE_NAME}} at {{SITE_URL}}. The responsible site owner is {{OWNER_NAME}}. The public creator name is {{CREATOR_NAME}}.']],
  ['heading'=>'2. Information we collect','paragraphs'=>['We collect information you provide, limited technical information needed to operate and secure the service, and records created when you use site features.'], 'items'=>['Account details such as username, display name, email, password hash, preferences, and verification status.','Profile, privacy, notification, healthy-play, and accessibility settings.','Virtual-currency ledger entries, game rounds, favorites, achievements, missions, and fictional statistics.','Membership, fixed-product, receipt, entitlement, refund, dispute, and provider-reference records; not full payment credentials.','Support, contact, sponsorship, and licensing messages.','Minimized security records such as session identifiers, rate-limit events, request IDs, and shortened or hashed network identifiers.','First-party aggregate page, feature, device-category, error-rate, conversion, and performance measurements when enabled.']],
  ['heading'=>'3. Why we use information','items'=>['Provide accounts, save progress, and deliver requested games and features.','Secure sessions, prevent abuse, enforce permissions, and investigate errors.','Maintain an auditable virtual ledger and prevent duplicate fictional balance changes.','Manage memberships, fixed entitlements, refunds, cancellations, receipts, and support.','Honor privacy, analytics, accessibility, healthy-play, pause, deletion, and export choices.','Meet applicable legal, tax, accounting, dispute, and recordkeeping duties.']],
  ['heading'=>'4. Payments and service providers','paragraphs'=>['Configured providers such as PayPal or Square process payment details under their own policies. {{SITE_NAME}} receives provider references and status information required to confirm a legitimate membership or fixed product. Payment secrets and full card details must remain with the provider. Email and hosting providers process limited information needed to provide those services under the Adult Owner’s configuration.']],
  ['heading'=>'5. Cookies and local storage','paragraphs'=>['We use strictly necessary session and security storage. Device preferences, age-confirmation timestamp and policy version, and minimal guest progress may be stored locally. Optional analytics or advertising storage is controlled by consent where required. See the Cookie Policy for details.']],
  ['heading'=>'6. Sharing and disclosure','paragraphs'=>['We do not sell personal information. We disclose limited information to configured processors, professional advisers, or authorities only when reasonably necessary, instructed by the Adult Owner, or required by law. Public profile information appears only according to your privacy choices.']],
  ['heading'=>'7. Retention and security','paragraphs'=>['Retention periods are configurable and should be no longer than needed for the stated purpose, security, accounting, legal obligations, and dispute handling. Passwords are hashed. Sensitive traffic should use HTTPS. Access is restricted by roles and logged. No service can promise absolute security.']],
  ['heading'=>'8. Your choices and rights','items'=>['Update profile, privacy, notification, and accessibility settings.','Opt out of optional first-party analytics where required.','Request a personal-data export.','Request account deletion, subject to legitimate retention exceptions.','Revoke sessions and change credentials.','Pause or self-exclude from game access.','Contact {{SUPPORT_EMAIL}} about access, correction, deletion, or other applicable privacy rights.']],
  ['heading'=>'9. Age and audience','paragraphs'=>['The service is configured for an audience of at least {{MINIMUM_AGE}}. Age confirmation is not KYC or identity verification, and the service does not collect identity documents from ordinary site users. If we learn an account does not meet the configured age requirement, we may restrict or delete it consistent with applicable law.']],
  ['heading'=>'10. Changes and contact','paragraphs'=>['Material changes use a new document version and may require renewed acceptance. Contact {{SUPPORT_EMAIL}} with privacy questions. The Adult Owner must insert any required privacy representative or regulator contact before launch.']],
 ],
];
