<?php
return [
 'title'=>'Subscription Terms','version'=>'draft-2','effective_date'=>'{{EFFECTIVE_DATE}}','summary'=>'Renewal, cancellation, daily play-money grants, entitlement, and payment terms for optional {{SITE_NAME}} memberships.','important_notice'=>'Eligible memberships include a fixed, disclosed daily Cozy Coin grant. Cozy Coins have no cash value and cannot be transferred, withdrawn, redeemed, or exchanged. Membership never changes game odds, theoretical return, or payout rules.',
 'sections'=>[
  ['heading'=>'1. Plans, daily grants, and prices','paragraphs'=>['Available plan names, benefits, fixed daily Cozy Coin grant, monthly or annual price, currency, taxes, and renewal schedule appear before checkout. Prices and future grant amounts are configured by the Adult Owner. Free users keep access to all standard games and ordinary free rewards.']],
  ['heading'=>'2. Recurring authorization','paragraphs'=>['By starting a paid subscription, you authorize the selected provider to charge the disclosed amount at the disclosed interval until cancellation. Provider approval and payment-method availability vary. The service does not store full payment credentials.']],
  ['heading'=>'3. Renewal and receipts','paragraphs'=>['Subscriptions renew automatically unless cancelled before the provider’s applicable cutoff. A receipt or provider record identifies each transaction. Local price edits do not necessarily change an existing provider subscription automatically. Material price changes require appropriate notice and provider handling.']],
  ['heading'=>'4. Daily Cozy Coin grants','paragraphs'=>['Cozy Club receives {{COZY_CLUB_DAILY_COINS}} extra Cozy Coins and Cozy Club Plus receives {{COZY_CLUB_PLUS_DAILY_COINS}} extra Cozy Coins once per eligible UTC date under the current plan configuration. The server uses an idempotent ledger reference so retries do not duplicate a grant. A fixed grant supplies additional play-money rounds but does not change any outcome, probability, paytable, theoretical return, payout multiplier, or healthy-play control.']],
  ['heading'=>'5. Cancellation','paragraphs'=>['You may request cancellation in the billing area. Cancellation normally stops future renewal while benefits and daily grants continue through the paid-through date, unless a refund, dispute, fraud response, provider rule, or applicable law requires a different result. Keep the cancellation confirmation.']],
  ['heading'=>'6. Failed payments and grace period','paragraphs'=>['If a renewal fails, the subscription may enter a clearly disclosed configurable grace period while the provider retries. Entitlements and future daily grants stop after expiration when payment is not recovered. Free account access, ordinary free rewards, and standard games remain.']],
  ['heading'=>'7. Refunds and disputes','paragraphs'=>['The Refund Policy and applicable law govern refunds. A completed refund or payment dispute may revoke or adjust the related paid entitlement and stop future daily grants. Previously spent fictional counters are not cash and cannot be refunded, redeemed, or converted. Duplicate provider events must not duplicate access, charges, or grants. Contact support before opening a dispute when practical.']],
  ['heading'=>'8. Provider and account changes','paragraphs'=>['Provider plan IDs map to local plans. Changing provider, plan, billing interval, or future daily grant amount may require notice, cancellation, and a new checkout. Only the Adult Owner may activate live payments, change merchant identity, payout destination, or production credentials.']],
  ['heading'=>'9. Contact','paragraphs'=>['Manage the subscription in billing or contact {{SUPPORT_EMAIL}}. Never send full payment credentials or provider passwords.']],
 ],
];
