<?php
return [
 'title'=>'Terms of Service','version'=>'draft-2','effective_date'=>'{{EFFECTIVE_DATE}}','summary'=>'The rules for using {{SITE_NAME}}, a play-money social casino and casino-game arcade.','important_notice'=>'No real-money gambling is offered. Virtual currency has no cash value and cannot be transferred, redeemed, withdrawn, or exchanged for anything of value. Cozy Coins are not sold separately; eligible memberships include a disclosed fixed daily grant.',
 'sections'=>[
  ['heading'=>'1. Agreement and owner review','paragraphs'=>['These terms form an agreement between the user and the legal owner identified as {{OWNER_NAME}}, subject to completion and review before launch. By using the service after the effective date, you agree to these terms and linked policies.']],
  ['heading'=>'2. Eligibility and age','paragraphs'=>['You must meet the configured minimum age of {{MINIMUM_AGE}} and have legal capacity to accept these terms. The service is intended for an adult audience. Age confirmation does not constitute identity verification.']],
  ['heading'=>'3. Play-money entertainment only','items'=>['No real-money wagers, deposits, cash prizes, withdrawals, or cash out.','No separate sale of Cozy Coins or Parlor Stars, and no paid spins, paid bets, or randomized paid rewards; eligible memberships may include a fixed daily Cozy Coin grant disclosed before checkout.','No conversion into money, cryptocurrency, gift cards, merchandise, or anything of value.','No user-to-user transfers, trades, sales, or pooled player gambling funds.','Membership and fixed products never improve odds, theoretical return, paytables, or payout multipliers.']],
  ['heading'=>'4. Accounts and security','paragraphs'=>['Provide accurate account information, protect credentials, and notify {{SUPPORT_EMAIL}} of suspected compromise. You are responsible for activity under your account unless applicable law provides otherwise. Administrators must use required two-factor authentication.']],
  ['heading'=>'5. Game operation','paragraphs'=>['The PHP server authoritatively validates game actions, generates outcomes, and records fictional balance changes. Client animations do not choose results. Published rules, configuration, probabilities, and paytables apply to each accepted round. Errors may be corrected using auditable ledger entries; fictional balances are not property or money.']],
  ['heading'=>'6. Memberships and fixed products','paragraphs'=>['Optional memberships provide defined lounge features and may include a fixed daily Cozy Coin grant as disclosed before checkout. Recurring plans are governed by Subscription Terms. One-time products have fixed contents and an entitlement description. Provider availability and approval are not guaranteed.']],
  ['heading'=>'7. Healthy use','paragraphs'=>['Do not chase fictional losses or rely on past outcomes to predict a future win. Session reminders, limits, cooldown, pause, and self-exclusion are available. The service may enforce limits and does not penalize taking a break.']],
  ['heading'=>'8. Acceptable conduct','paragraphs'=>['Follow the Acceptable Use Policy. Do not exploit, automate, tamper with, reverse engineer beyond rights granted by law, harass others, impersonate people, evade restrictions, or attempt unauthorized access.']],
  ['heading'=>'9. Proprietary rights','paragraphs'=>['Original code, artwork, branding, game presentation, text, and documentation are proprietary and all rights are reserved. Browser-delivered materials are inspectable, but that does not grant permission to copy, redistribute, resell, sublicense, or create a competing service. Third-party components remain under their own licenses.']],
  ['heading'=>'10. Availability and changes','paragraphs'=>['The service may be maintained, updated, secured, or discontinued. Game configurations and cosmetic features may change with appropriate disclosure. We do not promise uninterrupted or error-free operation.']],
  ['heading'=>'11. Disclaimers and liability','paragraphs'=>['The Adult Owner must adapt warranty disclaimers, limitations of liability, consumer-rights carve-outs, dispute rules, and governing law for {{JURISDICTION}}. Nothing in this template excludes rights or liability that cannot lawfully be excluded.']],
  ['heading'=>'12. Termination and contact','paragraphs'=>['You may stop using the service and request deletion. We may restrict accounts for security, policy violations, legal duties, or active self-exclusion, using proportionate review and appeal where appropriate. Contact {{SUPPORT_EMAIL}}.']],
 ],
];
