<?php
return [
 'title'=>'Virtual Currency Policy','version'=>'draft-2','effective_date'=>'{{EFFECTIVE_DATE}}','summary'=>'The exact rules for Cozy Coins and Parlor Stars at {{SITE_NAME}}.','important_notice'=>'Virtual currency has no cash value and cannot be transferred, redeemed, withdrawn, or exchanged for anything of value. Cozy Coins are not sold separately; eligible memberships include a disclosed fixed daily grant.',
 'sections'=>[
  ['heading'=>'1. Cozy Coins','paragraphs'=>['Cozy Coins are fictional, nontransferable game counters used only for play-money wagers and payouts inside supported games. They are not money, stored value, cryptocurrency, property, a prize, or an investment.'], 'items'=>['Granted free at account creation or guest start.','Granted through free daily rewards, missions, achievements, promotional grants, or auditable administrator adjustments.','Eligible memberships include the fixed daily amount disclosed before checkout; Cozy Coins are not priced or sold separately.','Deducted and awarded only by server-authoritative ledger entries.']],
  ['heading'=>'2. Parlor Stars','paragraphs'=>['Parlor Stars are fictional loyalty or achievement points for fixed cosmetic unlocks when configured. They are not wagerable and have no cash value. They cannot be purchased, transferred, sold, traded, withdrawn, or exchanged for paid membership or anything outside the service.']],
  ['heading'=>'3. No ownership or cash out','paragraphs'=>['A displayed balance is a revocable license to use a fictional site feature under these policies, subject to law. There is no cash-out, redemption, withdrawal, transfer, marketplace, gift-card conversion, merchandise conversion, crypto conversion, or user sale.']],
  ['heading'=>'4. Ledger integrity','paragraphs'=>['Every balance change uses an append-only auditable ledger with a unique reference and idempotency protection. Corrections use new entries rather than rewriting history. The service may reconcile a displayed balance against the ledger and correct technical errors.']],
  ['heading'=>'5. Expiration, pause, and deletion','paragraphs'=>['The Adult Owner must publish any lawful inactivity policy before use. Healthy-play pause or self-exclusion does not convert balances into value. Account deletion may permanently remove access after the configured recovery and retention process. Balances cannot be transferred before deletion.']],
  ['heading'=>'6. Prohibited conduct','items'=>['Do not sell, trade, transfer, broker, or advertise balances or accounts.','Do not use automation, duplication, replay, race conditions, multiple accounts, or exploits to obtain fictional balances.','Do not claim balances have monetary value or represent earnings.','Do not attempt to pressure another user to transfer an account.']],
  ['heading'=>'7. Membership daily grants and outcome neutrality','paragraphs'=>['Eligible membership increases only the number of Cozy Coins granted once per UTC day. It never changes a game result, win probability, theoretical return, paytable, payout multiplier, wager limit, or healthy-play control, and it never makes free users lose more often.']],
 ],
];
