<?php $profileSection='profile'; $recentGames=isset($data['recent_games'])&&is_array($data['recent_games'])?$data['recent_games']:array_slice(require dirname(__DIR__).'/partials/default-games.php',0,4); ?>
<header class="page-hero"><div class="shell page-hero-inner"><p class="eyebrow">Your favorite chair</p><h1>Profile</h1><p class="lede">Progress, cozy collections, and public details—all under your control.</p></div></header>
<section class="section shell profile-layout">
    <?php require __DIR__ . '/_sidebar.php'; ?>
    <div class="profile-content">
        <section class="card card-pad"><div class="section-heading"><div><p class="eyebrow">Welcome back</p><h2><?= $esc((string)($user['display_name'] ?? $user['username'] ?? 'Guest')) ?>’s corner</h2><p><?= $esc((string)($user['bio'] ?? 'Settling into the coziest tables in the Parlor.')) ?></p></div><a class="button button-ghost" href="<?= $url('settings.index', [], '/settings') ?>">Edit profile</a></div><div class="stats-grid"><div class="stat"><strong><?= $esc(number_format((int)($user['cozy_coins'] ?? 0))) ?></strong><span>Fictional Cozy Coins</span></div><div class="stat"><strong><?= $esc(number_format((int)($user['parlor_stars'] ?? 0))) ?></strong><span>Parlor Stars</span></div><div class="stat"><strong><?= $esc(number_format((int)($data['games_played'] ?? 0))) ?></strong><span>Completed rounds</span></div><div class="stat"><strong><?= $esc((string)($data['achievements_unlocked'] ?? 0)) ?></strong><span>Achievements</span></div></div></section>
        <section class="card card-pad"><div class="section-heading"><div><h2>Continue playing</h2><p>Recent fictional rounds from this account.</p></div><a href="<?= $url('games.recent', [], '/games/recent') ?>">View all</a></div><div class="game-grid u-grid-two"><?php foreach($recentGames as $game){require dirname(__DIR__).'/partials/game-card.php';} ?></div></section>
        <section class="two-column"><article class="card card-pad stack"><p class="eyebrow">Next reward</p><h2 class="heading-card-lg">Daily Cozy Coins are ready</h2><p class="muted">Free to claim, with no wager or purchase needed.</p><a class="button button-gold" href="<?= $url('rewards.index', [], '/rewards') ?>">Visit rewards</a></article><article class="card card-pad stack"><p class="eyebrow">Healthy play</p><h2 class="heading-card-lg">Your comfort controls</h2><p class="muted">Session reminder: <?= $esc((string)($user['preferences']['session_reminder_label'] ?? 'Off')) ?> · Daily limit: <?= $esc((string)($user['preferences']['daily_limit_label'] ?? 'Not set')) ?></p><a class="button button-ghost" href="<?= $url('responsible-play', [], '/responsible-play') ?>">Adjust limits</a></article></section>
    </div>
</section>
