<?php

declare(strict_types=1);

/**
 * The Purple Parlor game catalog. Values are intentionally data-driven so the
 * lobby, rules pages, API disclosures, simulations, and engine share one source.
 */

$game = static function (
    string $slug,
    string $name,
    string $category,
    string $engine,
    string $description,
    array $rules,
    array $paytable,
    array $probability,
    ?float $rtp,
    array $settings = [],
    array $wager = ['minimum' => 1, 'maximum' => 1000, 'increment' => 1],
): array {
    return [
        'slug' => $slug,
        'name' => $name,
        'category' => $category,
        'engine' => $engine,
        'description' => $description,
        'rules' => $rules,
        'tutorial' => [
            'Choose a fictional Cozy Coin wager or use Practice where available.',
            'Choose the displayed action; the PHP server generates and validates every result.',
            'Review the outcome, paytable, and recent-round summary. You may leave or take a break at any time.',
        ],
        'wager' => $wager + ['currency' => 'cozy_coins', 'cash_value' => false],
        'wager_increments' => $wager['increment'] === 0 ? [0] : [$wager['increment'], $wager['increment'] * 5, $wager['increment'] * 10],
        'paytable' => $paytable,
        'probability' => $probability,
        'theoretical_rtp' => $rtp,
        'rtp_method' => $rtp === null ? 'Not applicable: this is a wager-free practice game.' : 'Long-run mathematical estimate for the disclosed default rules; player choices can change realized return.',
        'configuration_schema' => ['type' => 'object', 'additionalProperties' => false, 'properties' => $settings],
        'settings' => $settings,
        'client_renderer' => 'server-outcome-v1',
        'animation_controller' => ['skippable' => true, 'speedOptions' => ['instant', 'quick', 'cozy'], 'reducedMotion' => true],
        'sound_manifest' => ['deal' => 'game-deal', 'win' => 'game-win-soft', 'loss' => 'game-loss-soft', 'action' => 'game-action'],
        'statistics' => ['rounds', 'wins', 'losses', 'pushes', 'fictional_wagered', 'fictional_returned', 'largest_fictional_win'],
        'simulation' => ['enabled' => $rtp !== null, 'defaultAction' => 'play', 'expectedRtp' => $rtp],
        'notices' => ['play_money_only' => true, 'no_cash_value' => true, 'server_authoritative' => true],
    ];
};

$free = ['minimum' => 0, 'maximum' => 0, 'increment' => 0];
$standard = ['minimum' => 1, 'maximum' => 1000, 'increment' => 1];

return [
    'plinko' => $game('plinko', 'Parlor Plinko', 'arcade', 'instant',
        'Drop a token through 8–16 server-generated left/right bounces into a disclosed multiplier bin.',
        ['Choose 8–16 rows and low, medium, or high variance.', 'Each peg has an independent 1/2 left and 1/2 right chance.', 'The landing bin determines the gross fictional return.'],
        ['low' => '0.52x–2.82x', 'medium' => '0.28x–5.64x', 'high' => '0.08x–14.10x'],
        ['peg' => ['left' => 0.5, 'right' => 0.5], 'distribution' => 'Binomial by selected row count'], 0.94,
        ['rows' => ['type' => 'integer', 'minimum' => 8, 'maximum' => 16, 'default' => 12], 'risk' => ['enum' => ['low','medium','high'], 'default' => 'medium']], $standard),

    'classic-three-reel-slots' => $game('classic-three-reel-slots', 'Royal Onion Reels', 'slots', 'instant',
        'An original three-reel, one-payline slot featuring onions, books, lavender, crowns, and hearth symbols.',
        ['All three center symbols must match.', 'Every reel uses the same disclosed 15-stop strip.', 'A win pays the listed gross multiplier.'],
        ['onion' => '8x', 'lavender' => '14x', 'book' => '22x', 'fireplace' => '33x', 'crown' => '55x', 'seven' => '136x'],
        ['reelStops' => 15, 'threeOfAKindOnly' => true, 'hitRate' => 0.056], 0.9508,
        ['theme' => ['enum' => ['royal_onion','cozy_fireplace'], 'default' => 'royal_onion']], $standard),

    'five-reel-video-slots' => $game('five-reel-video-slots', 'Moonlit Library Reels', 'slots', 'instant',
        'Five original reels form three rows and five fixed, equal-cost paylines with wild and scatter symbols.',
        ['Five fixed lines each receive one fifth of the wager.', 'Wins count matching symbols left-to-right; wild substitutes except for scatter.', 'Three or more scatters award a separate prize.'],
        ['line symbols' => '1.398x–104.85x by symbol and length', '3 scatters' => '13.98x', '4 scatters' => '69.9x', '5+ scatters' => '349.5x'],
        ['symbolWeights' => [25,22,18,14,10,6,3,2], 'paylines' => 5], 0.948,
        ['theme' => ['enum' => ['purple_parlor','moonlit_library','pixel_kingdom'], 'default' => 'moonlit_library']], $standard),

    'blackjack' => $game('blackjack', 'Velvet Blackjack', 'table', 'card',
        'Single-hand blackjack with dealer stand on all 17s and a server-shuffled 52-card deck.',
        ['Aces count as 1 or 11; faces count as 10.', 'Hit or stand; the dealer draws to 17 and stands on soft 17.', 'Natural blackjack returns 2.5x gross, ordinary win 2x, tie 1x.'],
        ['blackjack' => '2.5x', 'win' => '2x', 'push' => '1x', 'loss/bust' => '0x'],
        ['naturalBlackjack' => 0.0483, 'deck' => 'One 52-card deck shuffled every round', 'strategyDependent' => true, 'simpleHitTo17Estimate' => 0.94], 0.94,
        ['dealerRule' => ['const' => 'stand_soft_17']], $standard),

    'european-roulette' => $game('european-roulette', 'European Velvet Wheel', 'wheel', 'instant',
        'A 37-pocket single-zero wheel with straight, color, parity, range, and dozen wagers.',
        ['One of 0–36 is selected uniformly on the server.', 'Zero loses all even-money and dozen wagers.', 'Gross returns include the original fictional wager.'],
        ['straight' => '36x', 'red/black, odd/even, low/high' => '2x', 'dozen' => '3x'],
        ['pockets' => 37, 'straight' => '1/37', 'evenMoney' => '18/37', 'dozen' => '12/37'], 0.9730,
        ['bet' => ['enum' => ['straight','red','black','odd','even','low','high','dozen1','dozen2','dozen3']]], $standard),

    'american-roulette' => $game('american-roulette', 'American Plum Wheel', 'wheel', 'instant',
        'A 38-pocket 0/00 wheel with the standard generic roulette wager families.',
        ['One of 0, 00, and 1–36 is selected uniformly.', 'Both green pockets lose outside wagers.', 'This double-zero variant has a lower theoretical return than the European wheel.'],
        ['straight' => '36x', 'red/black, odd/even, low/high' => '2x', 'dozen' => '3x'],
        ['pockets' => 38, 'straight' => '1/38', 'evenMoney' => '18/38', 'dozen' => '12/38'], 0.9474,
        ['bet' => ['enum' => ['straight','red','black','odd','even','low','high','dozen1','dozen2','dozen3']]], $standard),

    'baccarat' => $game('baccarat', 'Parlor Baccarat', 'table', 'instant',
        'Punto banco using the fixed third-card table; choose Player, Banker, or Tie before the deal.',
        ['Card totals use the final digit only.', 'Naturals 8 or 9 stand; otherwise the standard third-card table is automatic.', 'Banker wins return 1.95x gross, Player 2x, Tie 9x.'],
        ['player' => '2x', 'banker' => '1.95x', 'tie' => '9x'],
        ['playerWin' => 0.4462, 'bankerWin' => 0.4586, 'tie' => 0.0952], 0.9876,
        ['bet' => ['enum' => ['player','banker','tie'], 'default' => 'player']], $standard),

    'craps' => $game('craps', 'Cozy Pass Line', 'dice', 'stateful',
        'A focused Pass Line craps round with a preserved server-side point state.',
        ['Come-out 7 or 11 wins; 2, 3, or 12 loses.', 'Any other total becomes the point.', 'Roll the point again before 7 to win.'],
        ['pass win' => '2x', 'loss' => '0x'],
        ['comeOutNatural' => '8/36', 'comeOutCraps' => '4/36', 'houseEdge' => 0.01414], 0.9859,
        ['bet' => ['const' => 'pass_line']], $standard),

    'video-poker' => $game('video-poker', 'Parlor Draw Poker', 'video_poker', 'card',
        'Five-card draw video poker with Jacks or Better, Deuces Wild, and Bonus Poker practice paytables.',
        ['Deal five, hold any cards, then draw once.', 'The selected variant paytable determines the gross fictional return.', 'Outcomes do not change based on membership or bot behavior.'],
        ['Jacks or Better' => '1x pair through 800x royal', 'Deuces Wild' => 'wild-deuce schedule', 'Bonus Poker' => 'enhanced four-of-a-kind awards'],
        ['royalFlushNatural' => '1/649,740', 'strategyDependent' => true], 0.9954,
        ['variant' => ['enum' => ['jacks_or_better','deuces_wild','bonus_poker'], 'default' => 'jacks_or_better']], $standard),

    'texas-holdem' => $game('texas-holdem', 'Parlor Hold’em Practice', 'poker', 'card',
        'Heads-up community-card poker against a clearly labeled computer opponent.',
        ['Two private cards and a shared five-card board form the best five-card hand.', 'Check to reveal turn and river or fold.', 'The computer has no access to future cards; Friendly reveals one hole card, Regular gives a broad made-hand hint, and Sharp gives neither.'],
        ['win' => '2x', 'split pot' => '1x', 'fold/loss' => '0x'],
        ['deck' => '52 cards without replacement', 'showdown' => 'standard best-five-of-seven ranking'], 1.0,
        ['difficulty' => ['enum' => ['friendly','regular','sharp'], 'default' => 'friendly']], $standard),

    'three-card-poker' => $game('three-card-poker', 'Three Card Parlor', 'poker', 'instant',
        'A streamlined three-card ante practice round using Trail, Pure Sequence, Sequence, Color, Pair, and High Card rankings.',
        ['Choose play or fold before the deal.', 'Dealer qualifies with Queen-high or better.', 'Player win and qualifying bonuses follow the disclosed table.'],
        ['dealer not qualified' => '1.5x', 'ordinary win' => '2x', 'Trail/Pure Sequence bonus' => 'additional 1x–4x'],
        ['dealerQualification' => 'Queen-high or pair+', 'deck' => '52 cards'], 0.99,
        ['decision' => ['enum' => ['play','fold'], 'default' => 'play']], $standard),

    'caribbean-stud' => $game('caribbean-stud', 'Island Hearth Stud', 'poker', 'card',
        'Five-card stud against the house with one dealer up-card and a generic qualifying rule.',
        ['Review five cards and choose raise or fold.', 'Dealer qualifies with Ace-King high or a pair.', 'A qualifying player win receives the disclosed hand bonus.'],
        ['dealer not qualified' => '1x', 'qualifying win' => '1.9x plus half of the 1x–51x hand bonus', 'push' => '1x'],
        ['dealerQualification' => 'Ace-King high or better', 'strategyDependent' => true, 'defaultRaisePolicyEstimate' => 0.84], 0.84,
        ['decision' => ['enum' => ['raise','fold']]], $standard),

    'casino-war' => $game('casino-war', 'Velvet Card War', 'card', 'card',
        'One high-card showdown; matching ranks offer a server-preserved War or surrender choice.',
        ['Higher rank wins.', 'After a tie, surrender returns half or War burns three and compares again.', 'A tie during War favors the player in this practice ruleset.'],
        ['ordinary win' => '2x', 'war win' => '1x because no additional stake is charged', 'surrender' => '0.5x', 'loss' => '0x'],
        ['initialTie' => '1/13', 'ordinaryComparisonSymmetric' => true], 0.972,
        ['tieChoice' => ['enum' => ['war','surrender']]], $standard),

    'red-dog' => $game('red-dog', 'Red Dog Practice', 'card', 'card',
        'Two ranked cards establish a spread; a third card wins when its rank lands strictly between them.',
        ['Same-rank or consecutive cards push immediately.', 'Otherwise draw one third card.', 'Smaller spreads award larger disclosed returns.'],
        ['pair match' => '12x; otherwise pair pushes', 'spread 1' => '6x', 'spread 2' => '5x', 'spread 3' => '3x', 'spread 4–11' => '2x'],
        ['deck' => '52 cards without replacement', 'conditionalWin' => 'four times the spread / 50 remaining cards'], 0.9081,
        [], $standard),

    'let-it-ride' => $game('let-it-ride', 'Let the Velvet Ride', 'poker', 'card',
        'A five-card poker practice variant with three initial units and two ride-or-pull decisions.',
        ['Three player cards combine with two community cards.', 'At each reveal, ride or pull one unit.', 'Tens-or-better and stronger hands use the disclosed schedule.'],
        ['tens or better' => '1:1 profit per riding unit', 'two pair' => '2:1', 'trips' => '3:1', 'straight' => '5:1', 'flush' => '8:1', 'full house' => '11:1', 'quads+' => '50:1–1000:1'],
        ['fiveCardPoker' => true, 'decisionStages' => 2, 'strategyDependent' => true], 0.967,
        [], $standard),

    'pai-gow-poker' => $game('pai-gow-poker', 'Two-Hand Pai Gow Practice', 'poker', 'instant',
        'Seven cards are automatically arranged into a five-card high hand and two-card low hand using a disclosed house-way approximation.',
        ['The high hand must outrank the low hand.', 'Win both comparisons to win; lose both to lose; split comparisons push.', 'The same deterministic arrangement method is used for player and dealer.'],
        ['win both' => '1.95x', 'split' => '1x', 'lose both' => '0x'],
        ['pushFrequency' => 'High because split comparisons push', 'commission' => '5% of gross even-money win'], 0.985,
        [], $standard),

    'hi-lo' => $game('hi-lo', 'Single-Card Hi-Lo', 'card', 'card',
        'Guess whether the next server-dealt rank is higher or lower than the visible card.',
        ['Suits do not matter.', 'A correct strict guess returns 1.9x.', 'Equal ranks push and return 1x.'],
        ['correct' => 'Probability-adjusted gross return shown before the guess', 'equal rank' => '1x', 'incorrect' => '0x'],
        ['tie' => '3/51 after first card', 'higher/lower depends on visible rank', 'targetReturn' => 0.95], 0.95,
        [], $standard),

    'five-card-draw' => $game('five-card-draw', 'Five Card Draw Bots', 'poker', 'card',
        'Classic five-card draw against a transparent rule-based computer opponent.',
        ['Hold any cards and draw once.', 'Friendly keeps made pairs only; Regular also keeps its highest card; Sharp also recognizes four-card flush draws.', 'Standard poker ranking determines the showdown; every opponent is explicitly computer-controlled.'],
        ['win' => '2x', 'push' => '1x', 'loss' => '0x'],
        ['deck' => '52 cards without replacement', 'bot' => 'Rule-based, not human'], 1.0,
        ['difficulty' => ['enum' => ['friendly','regular','sharp'], 'default' => 'regular']], $standard),

    'teen-patti-practice' => $game('teen-patti-practice', 'Three-Card Patti Practice', 'poker', 'instant',
        'A clearly labeled practice comparison inspired by the common three-card Trail-to-High-Card ranking family.',
        ['Each side receives three cards.', 'Rank order is Trail, Pure Sequence, Sequence, Color, Pair, High Card.', 'There is no real-money play and no social betting round.'],
        ['win' => '1.95x', 'tie' => '1x', 'loss' => '0x'],
        ['symmetricDeal' => true, 'deck' => '52 cards'], 0.975,
        [], $standard),

    'parlor-switch' => $game('parlor-switch', 'Parlor Hand Switch', 'table', 'card',
        'Original two-hand blackjack-inspired practice: optionally swap the second cards, then both hands and dealer auto-play to 17.',
        ['Receive two two-card hands.', 'Switch the second cards or keep them.', 'Both hands auto-hit below 17; dealer 22 pushes surviving hands.'],
        ['per-hand win' => '2x share', 'per-hand push/dealer 22' => '1x share', 'loss' => '0x'],
        ['twoHands' => true, 'dealer22Push' => true, 'strategyDependent' => true], 0.905,
        [], $standard),

    'sic-bo' => $game('sic-bo', 'Parlor Sic Bo', 'dice', 'instant',
        'Three dice support Small, Big, Odd, Even, specific Sum, and specific Triple wagers.',
        ['Triples lose Small, Big, Odd, and Even.', 'Sum and triple returns vary by rarity.', 'All three dice are generated independently on the server.'],
        ['small/big/odd/even' => '2x', 'sum' => '6x–61x', 'specific triple' => '181x'],
        ['outcomes' => 216, 'smallOrBigWin' => '105/216'], 0.9722,
        ['bet' => ['enum' => ['small','big','odd','even','sum','triple']]], $standard),

    'keno' => $game('keno', 'Lavender Keno', 'numbers', 'instant',
        'Pick 1–10 unique numbers from 1–80; the server draws 20 without replacement.',
        ['Picks must be unique.', 'Matches are the intersection of picks and 20 drawn numbers.', 'The paytable depends on both spots chosen and matches.'],
        ['1–10 spots' => 'See full spot/match matrix returned by rules API', 'maximum' => '32,800x on 10/10'],
        ['draw' => '20 of 80 without replacement', 'matchDistribution' => 'Hypergeometric'], 0.90,
        ['picks' => ['type' => 'array', 'minItems' => 1, 'maxItems' => 10, 'uniqueItems' => true]], $standard),

    'bingo' => $game('bingo', 'Parlor 75-Ball Bingo', 'numbers', 'instant',
        'A server-generated 5×5 card with a free center and 30 unique calls; completed rows, columns, and diagonals pay.',
        ['B/I/N/G/O columns use their standard 15-number ranges.', 'The center space is free.', 'Twelve possible lines are checked after 30 calls.'],
        ['1 line' => '4.44x', '2 lines' => '22.2x', '3+ lines' => '111x'],
        ['calls' => '30 of 75 without replacement', 'linesChecked' => 12], 0.92,
        [], $standard),

    'mines' => $game('mines', 'Moonlit Mines', 'arcade', 'stateful',
        'Reveal safe tiles on a 5×5 board and cash out before uncovering one of 1–10 hidden mines.',
        ['Mine locations are generated and stored only on the server.', 'Each safe reveal raises a probability-based multiplier.', 'Cash out after at least one safe tile; a mine returns zero.'],
        ['safe cashout' => '97% divided by cumulative survival probability', 'mine' => '0x'],
        ['board' => 25, 'mineRange' => [1,10], 'edge' => 0.03], 0.97,
        ['mines' => ['type' => 'integer', 'minimum' => 1, 'maximum' => 10, 'default' => 5]], $standard),

    'over-under-dice' => $game('over-under-dice', 'Over/Under D100', 'dice', 'instant',
        'Choose over or under a threshold from 2–98, then compare a uniform 0.00–99.99 server roll.',
        ['Under wins strictly below the target; Over wins at or above it.', 'The multiplier automatically reflects the selected probability.', 'A fixed 2% mathematical margin is disclosed.'],
        ['win' => '0.98 divided by win probability', 'loss' => '0x'],
        ['rolls' => 10000, 'uniform' => true, 'edge' => 0.02], 0.98,
        ['target' => ['type' => 'integer', 'minimum' => 2, 'maximum' => 98, 'default' => 50], 'choice' => ['enum' => ['under','over']]], $standard),

    'coin-flip' => $game('coin-flip', 'Golden Coin Flip', 'arcade', 'instant',
        'Choose heads or tails for a cryptographically generated equal-probability flip.',
        ['Heads and tails each have exactly one of two integer outcomes.', 'A correct guess returns 1.98x gross.', 'Past flips do not influence future flips.'],
        ['correct' => '1.98x', 'incorrect' => '0x'],
        ['heads' => 0.5, 'tails' => 0.5], 0.99,
        ['guess' => ['enum' => ['heads','tails']]], $standard),

    'prize-wheel' => $game('prize-wheel', 'Cozy Prize Wheel', 'wheel', 'instant',
        'A 16-segment uniform wheel with every segment and gross multiplier disclosed.',
        ['Every segment is equally likely.', 'The pointer index comes only from the server result.', 'Zero segments return no fictional coins.'],
        ['segments' => ['0x','0.25x','0.75x','0.75x','1x','1.5x','0x','2x','0.25x','0.75x','0x','2.5x','0.5x','1x','0x','4x']],
        ['segments' => 16, 'each' => '1/16'], 0.9531,
        [], $standard),

    'number-draw' => $game('number-draw', 'Parlor Number Draw', 'numbers', 'instant',
        'Guess a uniform two-digit number, its last digit, or its ten-number band.',
        ['Exact mode compares 0–99.', 'Last-digit and range modes each cover ten outcomes.', 'All modes target a 95% long-run return.'],
        ['exact' => '95x', 'last digit' => '9.5x', 'range' => '9.5x'],
        ['exact' => '1/100', 'lastDigit' => '1/10', 'range' => '1/10'], 0.95,
        ['mode' => ['enum' => ['exact','last_digit','range']]], $standard),

    'pachinko' => $game('pachinko', 'Lavender Pachinko', 'arcade', 'instant',
        'A 15-pin server-generated left/right path lands in one of 16 symmetric prize slots.',
        ['Each pin sends the ball left or right with equal probability.', 'Slot probability follows the 15-row binomial distribution.', 'The complete path is returned for animation.'],
        ['outer to center slots' => '50x, 20x, 8x, 4x, 2x, 1.2x, 0.7x, 0.43x'],
        ['pins' => 15, 'pathCount' => 32768, 'distribution' => 'Binomial'], 0.952,
        [], $standard),

    'horse-racing' => $game('horse-racing', 'Velvet Downs', 'simulation', 'instant',
        'Choose one of six fictional horses with disclosed weights; the server selects the winner and animates a cosmetic finish order.',
        ['Horse names and odds are fictional.', 'Winner weights are 25, 22, 19, 15, 11, and 8 out of 100.', 'Gross return equals 95% divided by the selected win probability.'],
        ['Lavender Bolt' => '3.8x', 'Golden Onion' => '4.31x', 'Velvet Comet' => '5x', 'Cozy Ember' => '6.33x', 'Moonlit Crown' => '8.63x', 'Royal Whisker' => '11.87x'],
        ['weights' => [25,22,19,15,11,8]], 0.95,
        ['horse' => ['type' => 'integer', 'minimum' => 0, 'maximum' => 5]], $standard),

    'scratch-cards' => $game('scratch-cards', 'Free Parlor Scratch', 'casual', 'instant',
        'A wager-free nine-panel matching card that awards practice score only, never wagerable currency.',
        ['Scratch/reveal all nine panels.', 'Three or more identical symbols award practice score.', 'There is no Cozy Coin wager or payout.'],
        ['3 matches' => '10 practice points', '4 matches' => '40 practice points', '5+ matches' => '100 practice points'],
        ['sixSymbols' => true, 'panels' => 9], null,
        [], $free),

    'memory-match' => $game('memory-match', 'Fireside Memory Match', 'casual', 'stateful',
        'A wager-free 16-card memory board with eight server-shuffled pairs.',
        ['Flip two different face-down cards.', 'Matching pairs stay visible; mismatches turn back over.', 'Clear all eight pairs with as few moves as possible.'],
        ['completion' => 'Practice score only; no virtual-currency payout'],
        ['pairs' => 8, 'cards' => 16], null,
        [], $free),

    'klondike-solitaire' => $game('klondike-solitaire', 'Velvet Klondike', 'solitaire', 'solitaire',
        'Wager-free Klondike with seven tableau columns, stock, waste, and four suit foundations.',
        ['Build tableau downward in alternating colors.', 'Only Kings enter empty tableau columns.', 'Build each foundation from Ace through King.'],
        ['completion' => 'Practice achievement only'],
        ['deck' => 52, 'tableauColumns' => 7], null,
        [], $free),

    'pyramid-solitaire' => $game('pyramid-solitaire', 'Royal Pyramid', 'solitaire', 'solitaire',
        'Wager-free Pyramid solitaire with a 28-card tableau and stock/waste pair removal.',
        ['Only uncovered cards may be selected.', 'Remove a King alone or two cards totaling 13.', 'Clear all 28 tableau cards to win.'],
        ['completion' => 'Practice achievement only'],
        ['tableauCards' => 28, 'targetSum' => 13], null,
        [], $free),

    'tripeaks-solitaire' => $game('tripeaks-solitaire', 'Moonlit TriPeaks', 'solitaire', 'solitaire',
        'Wager-free TriPeaks with 28 tableau cards, a stock, and rank-adjacent clearing.',
        ['Only uncovered tableau cards may be taken.', 'Take a rank one above or below the waste top; Ace wraps with King.', 'Clear all three peaks to win.'],
        ['completion' => 'Practice achievement only'],
        ['tableauCards' => 28, 'aceKingWrap' => true], null,
        [], $free),

    'freecell' => $game('freecell', 'Parlor FreeCell', 'solitaire', 'solitaire',
        'Wager-free FreeCell with eight visible columns, four free cells, and four suit foundations.',
        ['Move one exposed card per action.', 'Columns build downward in alternating colors.', 'Free cells hold one card; foundations build Ace through King.'],
        ['completion' => 'Practice achievement only'],
        ['columns' => 8, 'freeCells' => 4, 'openInformation' => true], null,
        [], $free),

    'higher-lower-streak' => $game('higher-lower-streak', 'Crown Streak', 'card', 'stateful',
        'Build a streak by guessing higher or lower, then cash out a rising disclosed multiplier.',
        ['Equal ranks safely continue the streak.', 'A wrong strict guess ends the round.', 'Cash out after at least one successful guess.'],
        ['cashout' => '0.95 divided by the cumulative disclosed survival probability, capped at 500x', 'wrong guess' => '0x'],
        ['deck' => '52 cards without replacement', 'strategyDependent' => true], 0.95,
        [], $standard),

    'gem-drop' => $game('gem-drop', 'Amethyst Gem Drop', 'arcade', 'instant',
        'A server-generated 6×6 gem board pays horizontal runs of three or more identical gems.',
        ['Five gem types are equally likely per cell.', 'Each row is scanned left-to-right for non-overlapping runs.', 'Longer runs add larger gross returns.'],
        ['3 run' => '0.965x', '4 run' => '1.93x', '5 run' => '2.895x', '6 run' => '3.86x'],
        ['cells' => 36, 'symbols' => 5, 'independentCells' => true], 0.93,
        [], $standard),

    'lucky-cups' => $game('lucky-cups', 'Lucky Lavender Cups', 'arcade', 'instant',
        'Pick one of three cups; a server-selected cup hides the golden onion.',
        ['Each cup is equally likely.', 'The shuffle order is cosmetic and cannot change the winning cup.', 'A correct pick returns 2.85x gross.'],
        ['correct' => '2.85x', 'incorrect' => '0x'],
        ['cups' => 3, 'each' => '1/3'], 0.95,
        ['cup' => ['type' => 'integer', 'minimum' => 1, 'maximum' => 3]], $standard),

    'treasure-tiles' => $game('treasure-tiles', 'Treasure Tiles', 'arcade', 'stateful',
        'Explore a 20-tile server-hidden map containing three traps and ten treasures, then bank the accumulated fictional return.',
        ['Trap and treasure positions remain server-only until completion.', 'Empty tiles are safe; treasure raises the cashout amount.', 'Cash out after finding treasure or lose the round on a trap.'],
        ['cashout' => '0.72x plus 0.17x per treasure point', 'trap' => '0x'],
        ['tiles' => 20, 'traps' => 3, 'treasures' => 10], 0.94,
        [], $standard),
];
