<?php

declare(strict_types=1);

/*
 * method, path, route name, handler, middleware aliases.
 * Dynamic path parameters use {name}; handlers are [class, method].
 */
return [
    ['GET', '/', 'home', ['PageController', 'home'], ['age']],
    ['GET', '/age', 'age.show', ['PageController', 'age']],
    ['POST', '/age', 'age.confirm', ['AccountController', 'confirmAge'], ['csrf', 'rate:age']],
    ['GET', '/guest/start', 'guest.start', ['AccountController', 'startGuest'], ['age']],

    ['GET', '/games', 'games.index', ['GameController', 'index'], ['age']],
    ['GET', '/games/all', 'games.all', ['GameController', 'index'], ['age']],
    ['GET', '/games/category/{category}', 'games.category', ['GameController', 'category'], ['age']],
    ['GET', '/games/search', 'games.search', ['GameController', 'search'], ['age']],
    ['GET', '/games/favorites', 'games.favorites', ['GameController', 'favorites'], ['auth', 'age']],
    ['GET', '/games/recent', 'games.recent', ['GameController', 'recent'], ['age']],
    ['GET', '/games/{slug}', 'games.show', ['GameController', 'show'], ['age']],
    ['POST', '/games/{slug}/favorite', 'games.favorite', ['GameController', 'favorite'], ['auth', 'csrf']],
    ['POST', '/favorites/{slug}', 'favorites.toggle', ['GameController', 'favorite'], ['auth', 'csrf']],

    ['GET', '/api/games', 'api.games.index', ['ApiGameController', 'index'], ['age', 'rate:api']],
    ['POST', '/api/games/{slug}/round', 'api.games.round', ['ApiGameController', 'round'], ['age', 'csrf', 'rate:game']],
    ['POST', '/api/games/{slug}/action', 'api.games.action', ['ApiGameController', 'action'], ['age', 'csrf', 'rate:game']],
    ['GET', '/fairness/verify', 'fairness.verify', ['GameController', 'verify'], ['age']],
    ['POST', '/fairness/verify', 'fairness.check', ['GameController', 'verifyResult'], ['csrf', 'rate:api']],

    ['GET', '/daily-rewards', 'rewards.index', ['EngagementController', 'rewards'], ['auth', 'age']],
    ['GET', '/rewards', 'rewards.dashboard', ['EngagementController', 'rewards'], ['auth', 'age']],
    ['POST', '/daily-rewards/claim', 'rewards.claim', ['EngagementController', 'claimReward'], ['auth', 'csrf', 'rate:reward']],
    ['GET', '/missions', 'missions.index', ['EngagementController', 'missions'], ['auth', 'age']],
    ['GET', '/missions/{id}', 'missions.show', ['EngagementController', 'mission'], ['auth', 'age']],
    ['POST', '/missions/{id}/claim', 'missions.claim', ['EngagementController', 'claimMission'], ['auth', 'csrf', 'rate:reward']],
    ['GET', '/achievements', 'achievements.index', ['EngagementController', 'achievements'], ['auth', 'age']],
    ['GET', '/leaderboards', 'leaderboards.index', ['EngagementController', 'leaderboards'], ['age']],

    ['GET', '/login', 'auth.login', ['AuthController', 'loginForm'], ['guest']],
    ['POST', '/login', 'auth.login.store', ['AuthController', 'login'], ['guest', 'csrf', 'rate:login']],
    ['POST', '/logout', 'auth.logout', ['AuthController', 'logout'], ['auth', 'csrf']],
    ['GET', '/register', 'auth.register', ['AuthController', 'registerForm'], ['guest', 'age']],
    ['POST', '/register', 'auth.register.store', ['AuthController', 'register'], ['guest', 'age', 'csrf', 'rate:registration']],
    ['GET', '/verify-email', 'auth.verify.notice', ['AuthController', 'verifyNotice']],
    ['GET', '/verify-email/{token}', 'auth.verify', ['AuthController', 'verify'], ['rate:verification']],
    ['POST', '/verify-email/resend', 'auth.verify.resend', ['AuthController', 'resendVerification'], ['csrf', 'rate:verification']],
    ['GET', '/forgot-password', 'auth.password.request', ['AuthController', 'forgotForm'], ['guest']],
    ['POST', '/forgot-password', 'auth.password.email', ['AuthController', 'forgot'], ['guest', 'csrf', 'rate:password-reset']],
    ['GET', '/reset-password/{token}', 'auth.password.reset', ['AuthController', 'resetForm'], ['guest']],
    ['POST', '/reset-password', 'auth.password.update', ['AuthController', 'reset'], ['guest', 'csrf', 'rate:password-reset']],
    ['GET', '/two-factor', 'auth.two-factor', ['AuthController', 'twoFactorForm']],
    ['POST', '/two-factor', 'auth.two-factor.verify', ['AuthController', 'verifyTwoFactor'], ['csrf', 'rate:login']],
    ['GET', '/confirm-password', 'auth.confirm-password', ['AuthController', 'confirmPasswordForm'], ['auth', 'csrf']],
    ['POST', '/confirm-password', 'auth.confirm-password.store', ['AuthController', 'confirmPassword'], ['auth', 'csrf', 'rate:login']],

    ['GET', '/profile', 'profile.show', ['AccountController', 'profile'], ['auth']],
    ['POST', '/profile', 'profile.update', ['AccountController', 'updateProfile'], ['auth', 'csrf']],
    ['POST', '/settings/profile', 'profile.update.settings', ['AccountController', 'updateProfile'], ['auth', 'csrf']],
    ['POST', '/settings/privacy', 'profile.privacy.update', ['AccountController', 'updatePrivacy'], ['auth', 'csrf']],
    ['POST', '/settings/preferences', 'profile.preferences.update', ['AccountController', 'updatePreferences'], ['auth', 'csrf']],
    ['POST', '/settings/notifications', 'profile.notifications.update', ['AccountController', 'updateNotifications'], ['auth', 'csrf']],
    ['POST', '/privacy/consent', 'privacy.consent', ['AccountController', 'privacyConsent'], ['csrf']],
    ['GET', '/statistics', 'statistics.index', ['AccountController', 'statistics'], ['auth']],
    ['GET', '/profile/statistics', 'profile.stats', ['AccountController', 'statistics'], ['auth']],
    ['GET', '/profile/statistics/export', 'profile.stats-export', ['AccountController', 'statisticsExport'], ['auth', 'reauth']],
    ['GET', '/profile/{username}', 'profile.public', ['AccountController', 'publicProfile'], ['age']],
    ['GET', '/u/{username}', 'profile.public.short', ['AccountController', 'publicProfile'], ['age']],
    ['GET', '/settings', 'settings.index', ['AccountController', 'settings'], ['auth']],
    ['POST', '/settings', 'settings.update', ['AccountController', 'updateSettings'], ['auth', 'csrf']],
    ['GET', '/settings/email', 'profile.email.edit', ['AccountController', 'emailChangeForm'], ['auth', 'reauth']],
    ['POST', '/settings/email', 'profile.email.update', ['AccountController', 'requestEmailChange'], ['auth', 'csrf', 'reauth', 'rate:verification']],
    ['GET', '/account/sessions', 'account.sessions', ['AccountController', 'sessions'], ['auth']],
    ['GET', '/settings/sessions', 'profile.sessions', ['AccountController', 'sessions'], ['auth']],
    ['DELETE', '/account/sessions/{id}', 'account.sessions.revoke', ['AccountController', 'revokeSession'], ['auth', 'csrf']],
    ['POST', '/settings/sessions/revoke-all', 'profile.sessions.revoke-all', ['AccountController', 'revokeAllSessions'], ['auth', 'csrf']],
    ['POST', '/settings/sessions/{id}/revoke', 'profile.sessions.revoke', ['AccountController', 'revokeSession'], ['auth', 'csrf']],
    ['POST', '/settings/password', 'profile.password.update', ['AccountController', 'updatePassword'], ['auth', 'csrf', 'reauth']],
    ['GET', '/settings/two-factor', 'auth.2fa.setup', ['AccountController', 'twoFactorSetup'], ['auth', 'reauth']],
    ['POST', '/settings/two-factor', 'auth.2fa.confirm', ['AccountController', 'twoFactorConfirm'], ['auth', 'csrf', 'reauth']],
    ['GET', '/settings/recovery-codes', 'auth.recovery-codes', ['AccountController', 'recoveryCodes'], ['auth', 'reauth']],
    ['POST', '/settings/recovery-codes', 'auth.recovery-codes.regenerate', ['AccountController', 'regenerateRecoveryCodes'], ['auth', 'csrf', 'reauth']],
    ['GET', '/account/delete', 'account.delete', ['AccountController', 'deleteForm'], ['auth']],
    ['DELETE', '/account', 'account.destroy', ['AccountController', 'delete'], ['auth', 'csrf', 'reauth']],
    ['POST', '/account/delete', 'profile.delete.confirm', ['AccountController', 'delete'], ['auth', 'csrf', 'reauth']],
    ['GET', '/account/export', 'account.export', ['AccountController', 'export'], ['auth', 'reauth']],
    ['POST', '/account/export', 'profile.export.request', ['AccountController', 'requestExport'], ['auth', 'csrf', 'reauth']],
    ['POST', '/account/pause', 'account.pause', ['AccountController', 'pause'], ['auth', 'csrf']],
    ['POST', '/account/take-a-break', 'account.break', ['AccountController', 'takeBreak'], ['csrf']],
    ['POST', '/account/balance-reset', 'account.balance-reset', ['AccountController', 'resetBalance'], ['auth', 'csrf', 'rate:reward']],
    ['POST', '/responsible-play/limits', 'responsible-play.limits', ['AccountController', 'playLimits'], ['auth', 'csrf']],
    ['POST', '/responsible-play/cooldown', 'responsible-play.cooldown', ['AccountController', 'cooldown'], ['auth', 'csrf']],
    ['POST', '/responsible-play/self-exclude', 'responsible-play.self-exclude', ['AccountController', 'selfExclude'], ['auth', 'csrf', 'reauth']],
    ['POST', '/report/profile/{username}', 'moderation.report-profile', ['SupportController', 'reportProfile'], ['auth', 'csrf', 'rate:contact']],

    ['GET', '/membership', 'membership.index', ['BillingController', 'plans'], ['age']],
    ['GET', '/shop', 'shop.index', ['BillingController', 'shop'], ['age']],
    ['GET', '/billing', 'billing.index', ['BillingController', 'billing'], ['auth']],
    ['GET', '/billing/checkout', 'billing.checkout', ['BillingController', 'checkoutForm'], ['auth']],
    ['GET', '/billing/purchases', 'billing.purchases', ['BillingController', 'purchases'], ['auth']],
    ['GET', '/billing/history', 'billing.history', ['BillingController', 'purchases'], ['auth']],
    ['GET', '/billing/subscription', 'billing.subscription', ['BillingController', 'subscription'], ['auth']],
    ['GET', '/billing/subscriptions', 'billing.subscriptions', ['BillingController', 'subscription'], ['auth']],
    ['POST', '/billing/checkout', 'billing.checkout.submit', ['BillingController', 'checkout'], ['auth', 'csrf', 'rate:payment']],
    ['POST', '/billing/subscribe', 'billing.subscribe', ['BillingController', 'subscribe'], ['auth', 'csrf', 'rate:payment']],
    ['POST', '/billing/subscription/cancel', 'billing.cancel', ['BillingController', 'cancel'], ['auth', 'csrf', 'reauth']],
    ['POST', '/billing/subscription/reactivate', 'billing.reactivate', ['BillingController', 'reactivate'], ['auth', 'csrf']],
    ['GET', '/billing/support', 'billing.support', ['BillingController', 'support'], ['auth']],
    ['POST', '/billing/support', 'billing.support.store', ['SupportController', 'billing'], ['auth', 'csrf', 'rate:contact']],
    ['GET', '/billing/return/{provider}', 'billing.return', ['BillingController', 'return'], ['auth']],
    ['GET', '/billing/cancel/{provider}', 'billing.provider-cancel', ['BillingController', 'providerCancel'], ['auth']],

    ['POST', '/api/webhooks/paypal', 'webhooks.paypal', ['WebhookController', 'paypal'], ['rate:webhook']],
    ['POST', '/api/webhooks/square', 'webhooks.square', ['WebhookController', 'square'], ['rate:webhook']],

    ['GET', '/help', 'help.index', ['PageController', 'help'], ['age']],
    ['GET', '/help/rules', 'help.rules', ['PageController', 'rules'], ['age']],
    ['GET', '/help/rules/{slug}', 'rules.show', ['GameController', 'rules'], ['age']],
    ['GET', '/help/probabilities', 'help.probabilities', ['PageController', 'probabilities'], ['age']],
    ['GET', '/probabilities', 'probabilities.index', ['PageController', 'probabilities'], ['age']],
    ['GET', '/probabilities/{slug}', 'probabilities.show', ['GameController', 'probability'], ['age']],
    ['GET', '/responsible-play', 'responsible-play', ['PageController', 'responsiblePlay'], ['age']],
    ['GET', '/take-a-break', 'take-a-break', ['PageController', 'takeBreak'], ['age']],
    ['GET', '/contact', 'contact.index', ['PageController', 'contact'], ['age']],
    ['POST', '/contact', 'contact.store', ['SupportController', 'contact'], ['age', 'csrf', 'rate:contact']],
    ['GET', '/sponsor', 'sponsor.index', ['PageController', 'sponsor'], ['age']],
    ['GET', '/licensing', 'licensing.index', ['PageController', 'licensing'], ['age']],
    ['POST', '/inquiries', 'inquiries.store', ['SupportController', 'inquiry'], ['age', 'csrf', 'rate:contact']],

    ['GET', '/legal/privacy', 'legal.privacy', ['PageController', 'legal']],
    ['GET', '/legal/terms', 'legal.terms', ['PageController', 'legal']],
    ['GET', '/legal/subscription-terms', 'legal.subscription', ['PageController', 'legal']],
    ['GET', '/legal/refunds', 'legal.refunds', ['PageController', 'legal']],
    ['GET', '/legal/virtual-currency', 'legal.virtual-currency', ['PageController', 'legal']],
    ['GET', '/legal/cookies', 'legal.cookies', ['PageController', 'legal']],
    ['GET', '/legal/advertising', 'legal.advertising', ['PageController', 'legal']],
    ['GET', '/legal/acceptable-use', 'legal.acceptable-use', ['PageController', 'legal']],
    ['GET', '/legal/copyright', 'legal.copyright', ['PageController', 'legal']],
    ['GET', '/legal/attributions', 'legal.attributions', ['PageController', 'legal']],

    ['GET', '/install', 'install.index', ['InstallController', 'index']],
    ['POST', '/install', 'install.run', ['InstallController', 'run'], ['csrf']],

    ['GET', '/admin', 'admin.dashboard', ['AdminController', 'dashboard'], ['auth', '2fa', 'can:admin.access']],
    ['GET', '/admin/users', 'admin.users', ['AdminController', 'section'], ['auth', '2fa', 'can:users.manage']],
    ['GET', '/admin/games', 'admin.games', ['AdminController', 'section'], ['auth', '2fa', 'can:games.manage']],
    ['GET', '/admin/rewards', 'admin.rewards', ['AdminController', 'section'], ['auth', '2fa', 'can:missions.manage']],
    ['GET', '/admin/commerce', 'admin.commerce', ['AdminController', 'section'], ['auth', '2fa', 'can:payments.summary.view']],
    ['GET', '/admin/content', 'admin.content', ['AdminController', 'section'], ['auth', '2fa', 'can:content.manage']],
    ['GET', '/admin/health', 'admin.health', ['AdminController', 'section'], ['auth', '2fa', 'can:system.health.view']],
    ['GET', '/admin/audit', 'admin.audit', ['AdminController', 'section'], ['auth', '2fa', 'can:audit.view']],
    ['GET', '/admin/settings', 'admin.settings', ['AdminController', 'section'], ['auth', '2fa', 'can:system.settings.manage']],
    ['GET', '/admin/audit/export', 'admin.audit.export', ['AdminController', 'auditExport'], ['auth', '2fa', 'reauth', 'can:audit.view']],
    ['GET', '/admin/commerce/activation', 'admin.commerce.activation', ['AdminController', 'commerceActivation'], ['auth', '2fa', 'reauth:adult_owner', 'can:payments.live.configure']],
    ['GET', '/admin/payments/activation-lock', 'admin.payments.lock.redirect', ['AdminController', 'paymentLockRedirect'], ['auth']],
    ['GET', '/admin/themes/{slug}/preview', 'admin.themes.preview', ['AdminController', 'previewTheme'], ['auth', '2fa', 'can:system.settings.manage']],
    ['GET', '/admin/managed-content/{type}/{key}/{id}/preview', 'admin.managed-content.preview', ['AdminController', 'previewManagedContent'], ['auth', '2fa', 'can:admin.access']],
    ['GET', '/admin/{section}', 'admin.section', ['AdminController', 'section'], ['auth', '2fa', 'can:admin.access']],
    ['POST', '/admin/settings', 'admin.settings.update', ['AdminController', 'settings'], ['auth', '2fa', 'csrf', 'can:system.settings.manage']],
    ['POST', '/admin/system/cache-clear', 'admin.cache.clear', ['AdminController', 'clearCache'], ['auth', '2fa', 'csrf', 'can:system.settings.manage']],
    ['POST', '/admin/health/check', 'admin.health.run', ['AdminController', 'runHealth'], ['auth', '2fa', 'csrf', 'can:system.health.view']],
    ['POST', '/admin/themes/{slug}', 'admin.themes.update', ['AdminController', 'updateTheme'], ['auth', '2fa', 'csrf', 'can:system.settings.manage']],
    ['POST', '/admin/payments/test/{provider}', 'admin.payments.test', ['AdminController', 'testPayment'], ['auth', '2fa', 'csrf', 'reauth', 'can:payments.live.configure']],
    ['POST', '/admin/payments/activation-lock', 'admin.payments.lock', ['AdminController', 'paymentLock'], ['auth', '2fa', 'csrf', 'reauth:adult_owner', 'can:payments.live.configure']],
    ['POST', '/admin/ledger/adjust', 'admin.ledger.adjust', ['AdminController', 'adjustLedger'], ['auth', '2fa', 'csrf', 'reauth', 'can:virtual_currency.adjust']],
    ['POST', '/admin/users/{id}/status', 'admin.users.status', ['AdminController', 'updateUserStatus'], ['auth', '2fa', 'csrf', 'can:users.manage']],
    ['POST', '/admin/users/{id}/roles', 'admin.users.roles', ['AdminController', 'updateUserRole'], ['auth', '2fa', 'csrf', 'reauth:adult_owner', 'can:users.roles.manage']],
    ['POST', '/admin/roles/{role}/permissions', 'admin.roles.permissions', ['AdminController', 'updateRolePermission'], ['auth', '2fa', 'csrf', 'reauth:adult_owner', 'can:users.roles.manage']],
    ['POST', '/admin/games/{id}', 'admin.games.update', ['AdminController', 'updateGame'], ['auth', '2fa', 'csrf', 'can:games.manage']],
    ['POST', '/admin/rewards/achievements/{id}', 'admin.achievements.update', ['AdminController', 'updateAchievement'], ['auth', '2fa', 'csrf', 'can:achievements.manage']],
    ['POST', '/admin/rewards/missions/{id}', 'admin.missions.update', ['AdminController', 'updateMission'], ['auth', '2fa', 'csrf', 'can:missions.manage']],
    ['POST', '/admin/rewards/daily', 'admin.rewards.daily', ['AdminController', 'updateDailyReward'], ['auth', '2fa', 'csrf', 'can:missions.manage']],
    ['POST', '/admin/catalog/{type}/{id}', 'admin.catalog.update', ['AdminController', 'updateCatalog'], ['auth', '2fa', 'csrf', 'reauth:adult_owner', 'can:payments.live.configure']],
    ['POST', '/admin/entitlements', 'admin.entitlements.update', ['AdminController', 'updateEntitlement'], ['auth', '2fa', 'csrf', 'reauth:adult_owner', 'can:payments.live.configure']],
    ['POST', '/admin/refund-requests/{id}', 'admin.refunds.track', ['AdminController', 'trackRefund'], ['auth', '2fa', 'csrf', 'reauth:adult_owner', 'can:payments.refund']],
    ['POST', '/admin/refund-requests/{id}/submit', 'admin.refunds.execute', ['AdminController', 'executeRefund'], ['auth', '2fa', 'csrf', 'reauth:adult_owner', 'can:payments.refund']],
    ['POST', '/admin/monetization/{type}/{id}', 'admin.monetization.update', ['AdminController', 'updateMonetization'], ['auth', '2fa', 'csrf', 'reauth:adult_owner', 'can:ads.manage']],
    ['POST', '/admin/requests/{type}/{id}', 'admin.requests.status', ['AdminController', 'updateRequestStatus'], ['auth', '2fa', 'csrf', 'can:admin.access']],
    ['POST', '/admin/workflows/{type}/{key}', 'admin.workflows.update', ['AdminController', 'updateWorkflow'], ['auth', '2fa', 'csrf', 'can:admin.access']],
    ['POST', '/admin/managed-content/{type}/{key}/draft', 'admin.managed-content.draft', ['AdminController', 'saveManagedContentDraft'], ['auth', '2fa', 'csrf', 'can:admin.access']],
    ['POST', '/admin/managed-content/{type}/{key}/{id}/approve', 'admin.managed-content.approve', ['AdminController', 'approveManagedLegal'], ['auth', '2fa', 'csrf', 'can:admin.access']],
    ['POST', '/admin/managed-content/{type}/{key}/{id}/publish', 'admin.managed-content.publish', ['AdminController', 'publishManagedContent'], ['auth', '2fa', 'csrf', 'can:admin.access']],
    ['POST', '/admin/managed-content/{type}/{key}/{id}/rollback', 'admin.managed-content.rollback', ['AdminController', 'rollbackManagedContent'], ['auth', '2fa', 'csrf', 'can:admin.access']],

    ['GET', '/maintenance', 'maintenance', ['PageController', 'maintenance']],
];
