<?php
$product=isset($data['product'])&&is_array($data['product'])?$data['product']:['id'=>'demo','name'=>'Cozy Club','description'=>'Fixed cosmetic and entertainment membership benefits.','price_label'=>'$2.99 / month','kind'=>'subscription'];
$payments=isset($data['payments'])&&is_array($data['payments'])?$data['payments']:['mode'=>'demo','paypal'=>['enabled'=>false],'square'=>['enabled'=>false]];
$mode=(string)($payments['mode']??'demo');
$dailyBonus=max(0,(int)($product['daily_bonus_coins']??0));
$includesDailyBonus=($product['kind']??'')==='subscription'&&$dailyBonus>0;
$isSubscription=($product['kind']??'')==='subscription';
$customerEmail=(string)($data['customer_email']??'');
?>
<header class="page-hero"><div class="shell page-hero-inner"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="<?= $url('billing.index', [], '/billing') ?>">Billing</a><span aria-hidden="true">/</span><span>Checkout</span></nav><p class="eyebrow"><?= $mode==='live'?'Provider checkout':($mode==='sandbox'?'Sandbox test':'Demonstration mode') ?></p><h1>Review checkout</h1><p class="lede"><?= $includesDailyBonus?'This recurring membership includes a fixed daily play-money grant. It never changes game odds or payouts.':'This fixed cosmetic purchase does not include virtual currency or change game odds.' ?></p></div></header>
<section class="section shell"><div class="billing-grid"><article class="card card-pad stack-lg"><div><p class="eyebrow">Order summary</p><h2><?= $esc($product['name']) ?></h2><p class="muted"><?= $esc($product['description']) ?></p></div><div class="split"><strong>Total</strong><strong class="price heading-price"><?= $esc($product['price_label']) ?></strong></div><?php if(($product['kind']??'')==='subscription'): ?><div class="callout"><strong>Recurring membership.</strong><p>The renewal schedule, cancellation instructions, grace period, refund rules, and fixed daily bonus are stated in <a href="<?= $url('legal.subscription', [], '/legal/subscription-terms') ?>">Subscription Terms</a>. You can cancel in billing.</p></div><?php endif; ?><?php if($includesDailyBonus): ?><div class="callout callout-gold"><strong><?= $esc(number_format($dailyBonus)) ?> extra Cozy Coins each UTC day.</strong><p>The server grants this once per eligible day. Coins are play-money only, have no cash value, cannot be transferred or purchased separately, and never improve odds or payout rules.</p></div><?php endif; ?><label class="checkbox-row"><input type="checkbox" id="checkout-terms" name="terms_accepted" value="1" required<?= $mode==='demo'?' form="demo-checkout"':'' ?>><span>I agree to the <a href="<?= $url('legal.terms', [], '/legal/terms') ?>">Terms</a><?php if(($product['kind']??'')==='subscription'): ?> and <a href="<?= $url('legal.subscription', [], '/legal/subscription-terms') ?>">Subscription Terms</a><?php endif; ?>, and understand <?= $includesDailyBonus?'the disclosed daily Cozy Coin grant is fictional, nontransferable, and has no cash value':'this purchase does not include virtual currency' ?>.</span></label><div class="callout callout-gold"><strong>No real-money gambling or cash out.</strong> Cozy Coins and Parlor Stars cannot be transferred, redeemed, withdrawn, or exchanged for anything of value.</div></article><aside class="stack">
<?php if($mode==='demo'): ?><section class="card card-pad stack"><span class="tag tag-gold">Demo only</span><h2 class="heading-card">Simulate checkout</h2><p class="muted">No payment provider is contacted and no real charge occurs.</p><form id="demo-checkout" method="post" action="<?= $url('billing.checkout.submit', [], '/billing/checkout') ?>" class="form-stack" data-demo-checkout><?= function_exists('csrf_field')?csrf_field():'' ?><input type="hidden" name="provider" value="demo"><input type="hidden" name="product_id" value="<?= $esc((string)$product['id']) ?>"><label class="field"><span>Demo result</span><select name="scenario"><option value="success">Successful payment</option><option value="failed">Failed payment</option><option value="cancelled">Cancelled checkout</option><option value="duplicate">Duplicate callback test</option></select></label><button class="button button-gold">Run demo checkout</button></form></section><?php endif; ?>
<?php $paypal=$payments['paypal']??[]; if(!empty($paypal['enabled'])): ?><section class="card card-pad stack" data-paypal-checkout data-mode="<?= $esc($mode) ?>" data-client-id="<?= $esc((string)($paypal['client_id']??'')) ?>" data-plan-id="<?= $esc((string)($paypal['plan_id']??'')) ?>" data-product-id="<?= $esc((string)$product['id']) ?>" data-complete-endpoint="<?= $url('billing.checkout.submit', [], '/billing/checkout') ?>"><span class="tag"><?= $mode==='live'?'PayPal':'PayPal sandbox' ?></span><h2 class="heading-card">Pay with PayPal</h2><div data-provider-status role="status">Checking PayPal availability…</div><div data-paypal-buttons></div></section><?php elseif($mode!=='demo'): ?><section class="card card-pad stack"><span class="status status-warning">PayPal unavailable</span><h2 class="heading-lg">PayPal is not configured</h2><p class="muted">The Adult Owner must finish provider setup before this option can be used.</p></section><?php endif; ?>
<?php $square=$payments['square']??[]; if(!empty($square['enabled'])): ?><section class="card card-pad stack" data-square-checkout data-mode="<?= $esc($mode) ?>" data-application-id="<?= $esc((string)($square['application_id']??'')) ?>" data-location-id="<?= $esc((string)($square['location_id']??'')) ?>" data-product-id="<?= $esc((string)$product['id']) ?>" data-kind="<?= $isSubscription?'subscription':'product' ?>" data-period="<?= $esc((string)($product['period']??'')) ?>" data-amount-cents="<?= $esc((string)($product['amount_cents']??0)) ?>" data-currency="<?= $esc((string)($product['currency']??'USD')) ?>" data-customer-email="<?= $esc($customerEmail) ?>" data-complete-endpoint="<?= $url('billing.checkout.submit', [], '/billing/checkout') ?>"><span class="tag"><?= $mode==='live'?'Square':'Square sandbox' ?></span><h2 class="heading-card"><?= $isSubscription?'Subscribe securely by card':'Pay securely by card' ?></h2><div data-provider-status role="status">Checking Square card availability…</div><div data-square-card></div><?php if($isSubscription): ?><label class="checkbox-row"><input type="checkbox" data-square-recurring-consent><span>I authorize Square to securely store this card and automatically charge <?= $esc($product['price_label']) ?> until I cancel. I can cancel from Billing.</span></label><?php endif; ?><div data-square-wallets hidden></div><button class="button button-gold button-wide" type="button" data-square-submit disabled><?= $isSubscription?'Start membership':'Pay '.$esc($product['price_label']) ?></button><p class="fine-print">Card details go directly to Square and are never stored by The Purple Parlor. Google Pay and Cash App Pay remain disabled unless separately approved and tested.</p></section><?php elseif($mode!=='demo'): ?><section class="card card-pad stack"><span class="status status-warning">Square unavailable</span><h2 class="heading-lg">Square card checkout is not configured</h2><p class="muted">The Adult Owner must finish provider setup before this method can be shown.</p></section><?php endif; ?>
<div class="notice notice-warning is-hidden" role="alert" data-billing-error></div></aside></div></section>
<?php if(!empty($payments['square']['enabled'])): ?><script src="<?= $esc($mode === 'live' ? 'https://web.squarecdn.com/v1/square.js' : 'https://sandbox.web.squarecdn.com/v1/square.js') ?>"></script><?php endif; ?>
<script type="module" src="<?= $assetUrl('js/billing.js') ?>"></script>
