<?php
declare(strict_types=1);
$emailTitle=(string)($emailTitle??'The Purple Parlor');
$emailPreheader=(string)($emailPreheader??'A message from The Purple Parlor.');
$emailContent=(string)($emailContent??'');
$app=isset($app)&&is_array($app)?$app:[];
$emailEsc=static fn(mixed $value):string=>htmlspecialchars((string)$value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');
$siteName=(string)($app['name']??'The Purple Parlor'); $creatorName=(string)($app['creator_name']??'Lord Funion'); $siteUrl=rtrim((string)($app['url']??'https://purpleparlor.lordfunion.dev'),'/'); $support=(string)($app['support_email']??'support@lordfunion.dev');
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title><?= $emailEsc($emailTitle) ?></title></head><body style="margin:0;background:#160c1f;color:#fff9e8;font-family:Segoe UI,Arial,sans-serif"><div style="display:none;max-height:0;overflow:hidden;opacity:0"><?= $emailEsc($emailPreheader) ?></div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#160c1f"><tr><td align="center" style="padding:30px 12px"><table role="presentation" width="600" cellspacing="0" cellpadding="0" style="width:100%;max-width:600px"><tr><td style="padding:18px 22px;text-align:center"><a href="<?= $emailEsc($siteUrl) ?>" style="color:#ffe2a0;text-decoration:none;font-family:Georgia,serif;font-size:28px;font-weight:bold">♛ <?= $emailEsc($siteName) ?></a><div style="color:#bba7c5;font-size:12px;letter-spacing:2px;text-transform:uppercase">By <?= $emailEsc($creatorName) ?></div></td></tr><tr><td style="border:1px solid #654171;border-radius:20px;background:#281432;padding:32px 28px;box-shadow:0 16px 40px rgba(0,0,0,.25)"><?= $emailContent ?></td></tr><tr><td style="padding:20px 12px;color:#bba7c5;font-size:12px;line-height:1.6;text-align:center"><p style="margin:0 0 8px"><strong style="color:#ffe2a0">Play-money only.</strong> Virtual currency has no cash value, is not sold separately, and cannot be transferred, redeemed, withdrawn, or exchanged for anything of value.</p><p style="margin:0">No real-money wagering or cash prizes. Need help? <a href="mailto:<?= $emailEsc($support) ?>" style="color:#d9b8ef"><?= $emailEsc($support) ?></a></p></td></tr></table></td></tr></table></body></html>
