<?php
$achievements = isset($data['achievements']) && is_array($data['achievements']) ? $data['achievements'] : [
 ['name'=>'First Chair','description'=>'Create your Parlor profile.','icon'=>'♛','unlocked'=>true,'date'=>'Earned today'],
 ['name'=>'Rules Reader','description'=>'Read ten complete game disclosures.','icon'=>'⌁','unlocked'=>true,'date'=>'Earned this week'],
 ['name'=>'Table Tour','description'=>'Try every table-game category.','icon'=>'♠','unlocked'=>false,'progress'=>'6 of 10'],
 ['name'=>'Quiet Victory','description'=>'Complete each solitaire style once.','icon'=>'♦','unlocked'=>false,'progress'=>'2 of 4'],
 ['name'=>'Cozy Regular','description'=>'Claim seven free daily rewards over time.','icon'=>'◉','unlocked'=>false,'progress'=>'3 of 7'],
 ['name'=>'Break Keeper','description'=>'Use healthy-play breaks five times.','icon'=>'☕','unlocked'=>false,'progress'=>'1 of 5'],
];
?>
<header class="page-hero"><div class="shell page-hero-inner"><p class="eyebrow">Moments, not pressure</p><h1>Achievements</h1><p class="lede">A scrapbook of fictional milestones. Achievements never affect game odds or unlock wagerable currency.</p><nav class="subnav" aria-label="Rewards sections"><a href="<?= $url('rewards.index', [], '/rewards') ?>">Daily reward</a><a href="<?= $url('missions.index', [], '/missions') ?>">Missions</a><a aria-current="page" href="<?= $url('achievements.index', [], '/achievements') ?>">Achievements</a><a href="<?= $url('leaderboards.index', [], '/leaderboards') ?>">Leaderboards</a></nav></div></header>
<section class="section shell"><div class="section-heading"><div><h2>Your collection</h2><p><?= $esc((string)($data['unlocked_count'] ?? 2)) ?> of <?= $esc((string)count($achievements)) ?> shown achievements unlocked.</p></div><label class="field"><span>Filter achievements</span><select><option>All achievements</option><option>Unlocked</option><option>In progress</option><option>Game-specific</option></select></label></div><div class="achievement-grid"><?php foreach($achievements as $achievement): ?><article class="achievement-card card<?= $achievement['unlocked'] ? '' : ' is-locked' ?>"><span class="achievement-medal" aria-hidden="true"><?= $esc($achievement['icon']) ?></span><div><div class="cluster"><h3><?= $esc($achievement['name']) ?></h3><span class="tag"><?= $achievement['unlocked'] ? 'Unlocked' : 'In progress' ?></span></div><p class="muted"><?= $esc($achievement['description']) ?></p><p class="fine-print"><?= $esc((string)($achievement['date'] ?? $achievement['progress'] ?? '')) ?></p></div></article><?php endforeach; ?></div></section>
