<?php
$missions = isset($data['missions']) && is_array($data['missions']) ? $data['missions'] : [
 ['id'=>'table-sampler','icon'=>'♠','name'=>'Table sampler','description'=>'Complete 3 rounds across any table games.','progress'=>2,'goal'=>3,'reward'=>'40 Parlor Stars','expires'=>'Resets Monday'],
 ['id'=>'rules-reader','icon'=>'⌁','name'=>'Know the room','description'=>'Read the complete rules and probability disclosure for two games.','progress'=>1,'goal'=>2,'reward'=>'Rules reader badge','expires'=>'No expiry'],
 ['id'=>'solitaire-finish','icon'=>'♦','name'=>'Quiet corner','description'=>'Finish a game of Klondike, FreeCell, or TriPeaks.','progress'=>0,'goal'=>1,'reward'=>'30 Parlor Stars','expires'=>'Resets Monday'],
 ['id'=>'healthy-break','icon'=>'☕','name'=>'A proper pause','description'=>'Use Take a Break after a play session.','progress'=>0,'goal'=>1,'reward'=>'Cozy cup profile pin','expires'=>'No expiry'],
];
?>
<header class="page-hero"><div class="shell page-hero-inner"><p class="eyebrow">Optional, never urgent</p><h1>Weekly missions</h1><p class="lede">Gentle goals based on fictional play, learning, and breaks. No paid missions and no loss-chasing prompts.</p><nav class="subnav" aria-label="Rewards sections"><a href="<?= $url('rewards.index', [], '/rewards') ?>">Daily reward</a><a aria-current="page" href="<?= $url('missions.index', [], '/missions') ?>">Missions</a><a href="<?= $url('achievements.index', [], '/achievements') ?>">Achievements</a><a href="<?= $url('leaderboards.index', [], '/leaderboards') ?>">Leaderboards</a></nav></div></header>
<section class="section shell"><div class="section-heading"><div><p class="eyebrow">Week in progress</p><h2><?= $esc((string)($data['week_label'] ?? 'Your current set')) ?></h2></div><p class="muted">Refreshes on server time. Completed progress is safe from changed device clocks.</p></div><div class="mission-list"><?php foreach($missions as $mission): $percent=min(100,(int)round(((int)$mission['progress']/max(1,(int)$mission['goal']))*100)); ?><article class="mission-card card"><span class="mission-icon" aria-hidden="true"><?= $esc($mission['icon']) ?></span><div class="stack"><div class="split"><div><h3><?= $esc($mission['name']) ?></h3><p class="muted"><?= $esc($mission['description']) ?></p></div><span class="tag tag-gold"><?= $esc($mission['reward']) ?></span></div><progress class="progress-native" aria-label="<?= $esc($mission['name']) ?> progress" max="<?= $esc((string)$mission['goal']) ?>" value="<?= $esc((string)$mission['progress']) ?>"><?= $esc((string)$mission['progress']) ?> of <?= $esc((string)$mission['goal']) ?></progress><p class="fine-print"><?= $esc((string)$mission['progress']) ?>/<?= $esc((string)$mission['goal']) ?> · <?= $esc($mission['expires']) ?></p></div><?php if((int)$mission['progress'] >= (int)$mission['goal']): ?><form method="post" action="<?= $url('missions.claim', ['id'=>$mission['id']], '/missions/'.$mission['id'].'/claim') ?>"><?= function_exists('csrf_field') ? csrf_field() : '' ?><button class="button button-small button-gold">Claim</button></form><?php else: ?><a class="button button-small button-ghost" href="<?= $url('missions.show', ['id'=>$mission['id']], '/missions/'.$mission['id']) ?>">Details</a><?php endif; ?></article><?php endforeach; ?></div></section>
