<?php
$cozyDaily = (int) ($app['cozy_club_daily_coins'] ?? 1000);
$plusDaily = (int) ($app['cozy_club_plus_daily_coins'] ?? 2500);
$plans = isset($data['plans']) && is_array($data['plans']) ? $data['plans'] : [
 ['slug'=>'free','name'=>'Free','monthly_cents'=>0,'annual_cents'=>0,'description'=>'The complete play-money arcade.','featured'=>false,'benefits'=>['Every standard game','Daily free Cozy Coins','Standard themes and profiles','Basic statistics','Cloud saving','Optional advertisements'],'daily_bonus_coins'=>0],
 ['slug'=>'cozy_club','name'=>'Cozy Club','monthly_cents'=>(int)($app['prices']['cozy_club_monthly']??299),'annual_cents'=>(int)($app['prices']['cozy_club_annual']??2999),'description'=>'A more personal, ad-free lounge with a fixed daily play-money bonus.','featured'=>true,'benefits'=>[number_format($cozyDaily).' extra Cozy Coins every UTC day','Advertisement-free experience','Royal Plum premium theme','Cozy Fireplace premium theme','Private per-game statistics','Club supporter profile badge'],'daily_bonus_coins'=>$cozyDaily],
 ['slug'=>'cozy_club_plus','name'=>'Cozy Club Plus','monthly_cents'=>(int)($app['prices']['cozy_club_plus_monthly']??599),'annual_cents'=>(int)($app['prices']['cozy_club_plus_annual']??5999),'description'=>'The full lounge collection with a larger fixed daily play-money bonus.','featured'=>false,'benefits'=>[number_format($plusDaily).' extra Cozy Coins every UTC day','Everything in Cozy Club','Downloadable statistics export','Expanded lounge layout','Animated profile crown'],'daily_bonus_coins'=>$plusDaily],
];
$billing=(string)($data['billing_period']??'monthly');
?>
<header class="page-hero"><div class="shell page-hero-inner"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="<?= $url('home', [], '/') ?>">Parlor</a><span aria-hidden="true">/</span><span>Memberships</span></nav><p class="eyebrow">Daily comfort perks, never better odds</p><h1>Choose your favorite chair.</h1><p class="lede">Every plan includes the complete standard game library. Paid plans add fixed lounge features and a disclosed daily Cozy Coin grant. Coins remain play-money only and never change odds or payout rules.</p></div></header>
<section class="section shell"><div class="section-heading"><div><h2>Membership plans</h2><p>Prices and availability are configured by the Adult Owner. Taxes may apply where required.</p></div><div class="subnav" aria-label="Billing period"><a<?= $billing==='monthly'?' aria-current="page"':'' ?> href="?billing=monthly">Monthly</a><a<?= $billing==='annual'?' aria-current="page"':'' ?> href="?billing=annual">Annual</a></div></div><div class="pricing-grid"><?php foreach($plans as $plan): $cents=$billing==='annual'?(int)$plan['annual_cents']:(int)$plan['monthly_cents']; ?><article class="price-card card<?= !empty($plan['featured'])?' featured':'' ?>"><?php if(!empty($plan['featured'])): ?><span class="tag tag-gold popular">Coziest pick</span><?php endif; ?><div><p class="eyebrow"><?= $esc($plan['name']) ?></p><h2><?= $esc($plan['description']) ?></h2></div><p class="price"><?= $cents===0?'$0':'$'.number_format($cents/100,2) ?><?php if($cents>0): ?><small>/<?= $billing==='annual'?'year':'month' ?></small><?php endif; ?></p><ul class="benefit-list"><?php foreach($plan['benefits'] as $benefit): ?><li><?= $esc($benefit) ?></li><?php endforeach; ?></ul><?php if($plan['slug']==='free'): ?><a class="button button-ghost" href="<?= $user?$url('games.index', [], '/games'):$url('auth.register', [], '/register') ?>"><?= $user?'Open lobby':'Create free account' ?></a><?php elseif(($user['membership_slug']??'')===$plan['slug']): ?><a class="button button-ghost" href="<?= $url('billing.index', [], '/billing') ?>">Manage current plan</a><?php else: ?><a class="button <?= !empty($plan['featured'])?'button-gold':'button-primary' ?>" href="<?= $url('billing.checkout', ['product'=>$plan['slug'],'period'=>$billing], '/billing/checkout?product='.rawurlencode($plan['slug']).'&period='.$billing) ?>">Choose <?= $esc($plan['name']) ?></a><?php endif; ?></article><?php endforeach; ?></div></section>
<section class="section-tight shell"><div class="callout callout-gold text-center"><h2 class="heading-card-lg">Membership never changes a game outcome.</h2><p>Subscribers receive the disclosed fixed daily balance grant, but never higher win probability, return-to-player percentages, payout multipliers, cash prizes, transfers, or fewer healthy-play controls.</p></div></section>
<section class="section shell"><div class="section-heading"><div><p class="eyebrow">Straight answers</p><h2>Membership questions</h2></div></div><div class="two-column"><div><details open><summary>Can I play every standard game for free?</summary><div>Yes. Standard games and the ordinary free daily reward do not require a paid membership.</div></details><details><summary>Does membership include Cozy Coins?</summary><div>Yes. Cozy Club receives <?= $esc(number_format($cozyDaily)) ?> extra Cozy Coins and Cozy Club Plus receives <?= $esc(number_format($plusDaily)) ?> extra Cozy Coins once per UTC day while eligible. These fictional counters have no cash value and cannot be transferred, withdrawn, redeemed, or bought separately.</div></details><details><summary>Can I cancel?</summary><div>Yes. Cancel in billing. Eligible benefits and daily grants normally continue through the paid-through date, subject to the published Subscription Terms.</div></details></div><div><details open><summary>Are memberships real-money wagers?</summary><div>No. They are fixed-price subscriptions for disclosed lounge features and a fixed play-money grant. The payment is never a wager and no prize or cash-out exists.</div></details><details><summary>Will prices or bonuses change?</summary><div>The Adult Owner may update prices or future daily grant amounts with proper notice. Existing provider subscriptions do not necessarily change automatically.</div></details><details><summary>Who handles payments?</summary><div>Configured providers process payment details. The Purple Parlor does not display or store full card credentials. Provider availability differs for recurring subscriptions and fixed purchases.</div></details></div></div></section>
